<?php
if(isset($title)){echo "<h1>$title</h1>";}
if(!empty($item)){
    $this->LoadComponent($component, "comp");
    $this->comp->$comp_action($component, $item);
}else{
    echo "<h1>Nenhum conteúdo encontrado</h1>";
    echo "<p>Não existe nenhum conteúdo relacionado nesta seção</p>";
}
$gui = new \classes\Component\GUI();

$opt = array('class' => 'span12', 'plugin' => $item['plugnome'], 'title' => "Acessos diários do Plugin $item[pluglabel]");
    classes\Component\widget::executeWidgets(array(
        'plugins/plug/widgets/reportWidget' => $opt,
    ));
?>