<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:47.
 */
class conexaoSetupTest extends PHPUnit_Framework_TestCase {

    /**
     * @var conexaoSetup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new conexaoSetup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers conexaoSetup::needExecute
     * @todo   Implement testNeedExecute().
     */
    public function testNeedExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conexaoSetup::setupSystem
     * @todo   Implement testSetupSystem().
     */
    public function testSetupSystem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conexaoSetup::checkCurrentConnection
     * @todo   Implement testCheckCurrentConnection().
     */
    public function testCheckCurrentConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
