<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:46.
 */
class webmasterSetupTest extends PHPUnit_Framework_TestCase {

    /**
     * @var webmasterSetup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new webmasterSetup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webmasterSetup::setupSystem
     * @todo   Implement testSetupSystem().
     */
    public function testSetupSystem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webmasterSetup::needExecute
     * @todo   Implement testNeedExecute().
     */
    public function testNeedExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webmasterSetup::hasWebmaster
     * @todo   Implement testHasWebmaster().
     */
    public function testHasWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
