<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:30.
 */
class plugins_actionModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plugins_actionModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plugins_actionModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers plugins_actionModel::isPublic
     * @todo   Implement testIsPublic().
     */
    public function testIsPublic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_actionModel::geraMenu
     * @todo   Implement testGeraMenu().
     */
    public function testGeraMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_actionModel::prepare_action
     * @todo   Implement testPrepare_action().
     */
    public function testPrepare_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_actionModel::getCodActionByName
     * @todo   Implement testGetCodActionByName().
     */
    public function testGetCodActionByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_actionModel::updateAction
     * @todo   Implement testUpdateAction().
     */
    public function testUpdateAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
