<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:35.
 */
class plugins_plugModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plugins_plugModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plugins_plugModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers plugins_plugModel::listPlugins
     * @todo   Implement testListPlugins().
     */
    public function testListPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::findPlugins
     * @todo   Implement testFindPlugins().
     */
    public function testFindPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::IsAvaible
     * @todo   Implement testIsAvaible().
     */
    public function testIsAvaible() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::IsRegistered
     * @todo   Implement testIsRegistered().
     */
    public function testIsRegistered() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::setSubplugins
     * @todo   Implement testSetSubplugins().
     */
    public function testSetSubplugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::getDefault
     * @todo   Implement testGetDefault().
     */
    public function testGetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::setDefault
     * @todo   Implement testSetDefault().
     */
    public function testSetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::getSystemPlugins
     * @todo   Implement testGetSystemPlugins().
     */
    public function testGetSystemPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::unregisterDropedPlugins
     * @todo   Implement testUnregisterDropedPlugins().
     */
    public function testUnregisterDropedPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::registerFoundedPlugins
     * @todo   Implement testRegisterFoundedPlugins().
     */
    public function testRegisterFoundedPlugins() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::getPluginInstaller
     * @todo   Implement testGetPluginInstaller().
     */
    public function testGetPluginInstaller() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::getOutdated
     * @todo   Implement testGetOutdated().
     */
    public function testGetOutdated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_plugModel::updateall
     * @todo   Implement testUpdateall().
     */
    public function testUpdateall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
