<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:30.
 */
class plugins_permissaoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plugins_permissaoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plugins_permissaoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers plugins_permissaoModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_permissaoModel::getCodPermissionByName
     * @todo   Implement testGetCodPermissionByName().
     */
    public function testGetCodPermissionByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
