<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:43.
 */
class plugins_modelModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plugins_modelModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plugins_modelModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers plugins_modelModel::unstall
     * @todo   Implement testUnstall().
     */
    public function testUnstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_modelModel::getCodModelByName
     * @todo   Implement testGetCodModelByName().
     */
    public function testGetCodModelByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_modelModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
