<?php 

$dados = array(
    'bd_name' => array(
        'name'    => 'Nome Do Banco de dados',
        'type'    => 'varchar',
        'default' => 'hat',
        'notnull' => true
    ),
    'bd_server' => array(
        'name'    => 'Servidor',
        'type'    => 'varchar',
        'default' => 'localhost',
        'notnull' => true
    ),
    'bd_user' => array(
        'name'    => 'Usuario',
        'type'    => 'varchar',
        'default' => 'root',
        'notnull' => true
    ),
    'bd_password' => array(
        'name'     => 'Senha',
        'type'     => 'varchar',
        'especial' => 'senha'
    )
);

$values = (isset($values))?$values:array();
$this->LoadResource('formulario','form');
$this->form->NewForm($dados, $values, array(), false, $url_action);
