<?php

echo "<h2>{$grupo['name']}</h2><hr/>";

$this->LoadJsPlugin('formulario/jqueryvalidate', 'jqval');
if(!empty($files)){
    $this->LoadResource('formulario', 'form');
    $this->LoadModel('site/configuracao', 'model');
    echo "<div class='config'>";
    foreach($files as $file){
        $this->form->printable();
        $url     = URL . "index.php?url=site/configuracao/configure/{$file['cod_cfile']}";
        $dados   = $this->model->LoadFileForm($file['cod_cfile']);
        $values  = $this->model->LoadFileValue($file['cod_cfile']);
        //die();
        if(isset($next_page)){
            $this->jqval->addToSuccess("
                    window.location.href = '$next_page';
            ");
        }
        if(isset($previous_page)){
            $dados['butt'] = array(
                'button_type' => 'Button',
                "button"      => "Anterior"
            );
            if(isset($dados['button'])) unset($dados['button']);
        }
        $dados['button'] = array("button" => "Próximo");
        
        $html   = $this->form->NewForm($dados, $values, array(), true, $url);
        $id     = "form_{$file['cod_cfile']}";
        echo "
            <div class='subitem'> 
                <div class='title'>{$file['title']} </div>
                <div class='descricao'>{$file['descricao']}</div>
                <div class='formcontainer' id='$id'>$html</div>
            </div>
        ";
    }
    echo "</div>";
}

$str = isset($previous_page)?"window.location.href = '$previous_page'":'';
$this->Html->LoadJqueryFunction("
    $('#execute').click(function(event){
        event.preventDefault();
        $str
    });
");

?>
<style type="text/css">
    
    .subitem{
        margin-bottom: 18px;
    }

    .subitem > .title{
        font-size: 18px;
        margin-bottom: 3px;
    }
    
    .subitem > .descricao{
        font-size: 14px;
        margin-bottom: 6px;
    }
   
    
</style>