<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:09:49.
 */
class plugins_setupModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plugins_setupModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plugins_setupModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers plugins_setupModel::getBasicModules
     * @todo   Implement testGetBasicModules().
     */
    public function testGetBasicModules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::dbInstall
     * @todo   Implement testDbInstall().
     */
    public function testDbInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::setModelName
     * @todo   Implement testSetModelName().
     */
    public function testSetModelName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::CheckBasicTables
     * @todo   Implement testCheckBasicTables().
     */
    public function testCheckBasicTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::checkInstalation
     * @todo   Implement testCheckInstalation().
     */
    public function testCheckInstalation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::isInstalled
     * @todo   Implement testIsInstalled().
     */
    public function testIsInstalled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::hasDbConnection
     * @todo   Implement testHasDbConnection().
     */
    public function testHasDbConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::basicInstall
     * @todo   Implement testBasicInstall().
     */
    public function testBasicInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::hasWebmaster
     * @todo   Implement testHasWebmaster().
     */
    public function testHasWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::setWebmaster
     * @todo   Implement testSetWebmaster().
     */
    public function testSetWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::getWebmasterData
     * @todo   Implement testGetWebmasterData().
     */
    public function testGetWebmasterData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::getDados
     * @todo   Implement testGetDados().
     */
    public function testGetDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plugins_setupModel::getTable
     * @todo   Implement testGetTable().
     */
    public function testGetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
